# Generated by Django 4.2.16 on 2025-04-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionhopital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='services',
        ),
    ]
