# Generated by Django 4.2.16 on 2025-04-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionhopital', '0002_remove_departement_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('contact', 'Contact général'), ('consultation', 'Demande de consultation')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('sujet', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
