# Generated by Django 4.2.16 on 2025-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionhopital', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
