# Generated by Django 4.2.16 on 2025-04-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionhopital', '0005_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('type', models.CharField(choices=[('article', 'Article'), ('evenement', 'Événement'), ('annonce', 'Annonce')], max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
